version: '3'

services:
  faker:
    container_name: mimesis
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: mimesis
      SLEEP_TIME: 20

networks:
  default:
    external:
      name: kafka-network
